name: LEURN

channels:
    - defaults
    - nvidia
    - conda-forge

dependencies:
    - pip=21.1.3
    - python=3.7.10
    - nvidia::cuda-nvcc=11.4
    - conda-forge::cudatoolkit=11.4
    - conda-forge::cudnn=8.1
    - scikit-learn
    - openml

    - pip:
          - tensorflow>=2.9.1
          - numpy
          - scipy
          - matplotlib
          - openpyxl
          - pandas
